### create users
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "document":"1037651327",
  "name": "Santiago Soto",
  "age": "28",
  "country": "Colombia",
  "services": "Xbox One X",
  "email": "santiago@gmail.com"
}

###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "document": "1037651321",
  "name": "Diego Martinez",
  "age": "25",
  "country": "Chile",
  "services": "Xbox One",
  "email": "diegomartinez@gmail.com"
}

###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "document": "12342345566",
  "name": "Miguel Alvarez",
  "age": "22",
  "country": "Peru",
  "services": "Xbox X",
  "email": "miguel@gmail.com"
}

//-------------------------------------------------
### para buscar todos las personas
 GET http://localhost:3000/api/users HTTP/1.1


//-------------------------------------------------
### para buscar por documento
 GET http://localhost:3000/api/user/1037651327 HTTP/1.1


//-------------------------------------------------
### para modificar con el id entregado
 PUT http://localhost:3000/api/users/642e227848b51d0e9562aeb0 HTTP/1.1
Content-Type: application/json

{
  "document": "1037651321",
  "name": "Diego Martinez",
  "age": "25",
  "country": "Chile",
  "services": "Xbox One",
  "email": "diegomartinez@gmail.com"
}

//-------------------------------------------------
### para eliminar por id
 DELETE http://localhost:3000/api/users/641b755eb33e57d4c18bbcc0 HTTP/1.1



 //--------------------------------------CASES ----------------------------------------
 
### crea un caso
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "7064852615",
  "description": "this is services to fix a xbox one, becase doesn't work hdmi port",
  "services": "Xbox One S",
  "email": "santiago@gmail.com"
}

###
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "1930956101",
  "description": "new case -- this is services to fix a xbox one, becase doesn't work hdmi port",
  "services": "Xbox One XS",
  "email": "diego@gmail.com"
}

###
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "5542985449",
  "description": "this is services to fix a xbox one, becase doesn't work hdmi port",
  "services": "Xbox One",
  "email": "santiago@gmail.com"
}


### para buscar todos los casos
GET http://localhost:3000/api/cases HTTP/1.1


### para buscar casos por documento
GET http://localhost:3000/api/cases/5542985449 HTTP/1.1

//--------------------------------------PERSON----------------------------------------

### para buscar todos las personas
 GET http://localhost:3000/api/person HTTP/1.1

### para buscar por cedula 
 GET http://localhost:3000/api/person/5542985449 HTTP/1.1

### para actualizar por cedula unicamente con los datos que envia
PATCH  http://localhost:3000/api/person/5542985449 HTTP/1.1
Content-Type: application/json

 {
    "name": "Corbie Ofield",
    "email": "worsting@gmail.com",
    "age": 38,
    "gender": "male",
    "contact": "3005106167",
    "address": "52 Grim Drive"
  }

//--------------------------------------EMPLOYEE----------------------------------------

### para buscar todos las empleados
 GET http://localhost:3000/api/employee HTTP/1.1

### para buscar por username
 GET http://localhost:3000/api/employee/santiago
