### create user
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "country": "Mexico",
  "services": "Xbox X",
	"personId": "6431c63e77120a24f5c18bb5"
}


//-------------------------------------------------
### para buscar todos los clientes
 GET http://localhost:3000/api/users HTTP/1.1


//-------------------------------------------------
### para buscar clientes por documento
 GET http://localhost:3000/api/user/7064852615 HTTP/1.1


//-------------------------------------------------
### para modificar con el id entregado NO USAR
 PUT http://localhost:3000/api/users/642e227848b51d0e9562aeb0 HTTP/1.1
Content-Type: application/json

{
  "document": "1037651321",
  "name": "Diego Martinez",
  "age": "25",
  "country": "Chile",
  "services": "Xbox One",
  "email": "diegomartinez@gmail.com"
}

//-------------------------------------------------
### para eliminar por id
 DELETE http://localhost:3000/api/users/641b755eb33e57d4c18bbcc0 HTTP/1.1



 //--------------------------------------CASES ----------------------------------------
 
### crea un caso
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "7064852615",
  "description": "i need to request a guarantee for my service",
  "type": "PQRS"
}

###
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "1930956101",
  "description": "we have sent technical to your place",
  "type": "Support"
}

###
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json

{
  "document": "5917603134",
  "description": "i need to take off my services",
  "type": "take off"
}


### para buscar todos los casos
GET http://localhost:3000/api/cases HTTP/1.1


### para buscar casos por documento
GET http://localhost:3000/api/cases/5542985449 HTTP/1.1

//--------------------------------------PERSON----------------------------------------

### para crear una persona

 POST  http://localhost:3000/api/person HTTP/1.1
Content-Type: application/json

{
  "document":"4339921831",
  "name":"Sofia Feilden",
  "email":"previews@gmail.com",
  "age":"68",
  "gender":"female",
  "contact":"3007392492",
  "address":"25362 Linden Center"
}

### crea un usuario con el id de persona
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "country": "Chile",
  "services": "Computer",
	"personId": "6431cf70276e53b3d16291c2"
}




### para buscar todos las personas
 GET http://localhost:3000/api/person HTTP/1.1

### para buscar persona por cedula 
 GET http://localhost:3000/api/person/1037651327 HTTP/1.1

### para actualizar por cedula unicamente con los datos que envia
PATCH  http://localhost:3000/api/person/1037651321 HTTP/1.1
Content-Type: application/json

 {
    "name": "Diego Martinez",
    "email": "diiegomartinez@gmail.com",
    "age": 38,
    "gender": "no-biniary",
    "contact": "3005106133",
    "address": "55 Grim Drive"
  }

//--------------------------------------EMPLOYEE----------------------------------------

### para buscar todos las empleados
 GET http://localhost:3000/api/employee HTTP/1.1

### para buscar por username
 GET http://localhost:3000/api/employee/santiago

### para actualizar por cedula la nueva contrasenia
PATCH  http://localhost:3000/api/employee/diego HTTP/1.1
Content-Type: application/json

 {
    "password": "diego2"
  }